using Diwire.Abstraction;
using Diwire.Abstraction.Attributes;

namespace DiwireSample.MyServices
{
    [RegisterType(typeof(IClock), typeof(Clock))]
    [RegisterType(typeof(IFooService), typeof(FooService), Diwire.Lifetime.Transient)]
    public class MyServicesModule : IModule
    {
        public void RegisterTypes(Diwire.Abstraction.IContainerRegistry containerRegistry)
        {
            // This Code was generated by Diwire;
            containerRegistry.RegisterSingleton<DiwireSample.MyServices.IClock>(_ => new DiwireSample.MyServices.Clock());
            containerRegistry.RegisterTransient<DiwireSample.MyServices.IFooService>(_ => new DiwireSample.MyServices.FooService(_.Resolve<DiwireSample.MyServices.IClock>()));
        }
    }
}
